version: '2'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
  selenium:
    image: selenium/standalone-chrome-debug:2.53.1
    ports:
      - 15900:5900
